<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="IL-MF10-NA102OH" ignored="0" name="Test" tests="9" failures="2" timestamp="24 Jul 2019 10:19:16 GMT" time="0.09" errors="0">
  <testcase name="Test1" time="0.01" classname="naveenSeleniumClass.FailedTestCase">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.01" classname="naveenSeleniumClass.FailedTestCase">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.0" classname="naveenSeleniumClass.FailedTestCase">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.01" classname="naveenSeleniumClass.FailedTestCase">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at naveenSeleniumClass.FailedTestCase.Test1(FailedTestCase.java:10)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase name="Test2" time="0.0" classname="naveenSeleniumClass.FailedTestCase">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.0" classname="naveenSeleniumClass.FailedTestCase">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.0" classname="naveenSeleniumClass.FailedTestCase">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.0" classname="naveenSeleniumClass.FailedTestCase">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at naveenSeleniumClass.FailedTestCase.Test2(FailedTestCase.java:15)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase name="Test3" time="0.0" classname="naveenSeleniumClass.FailedTestCase"/>
</testsuite> <!-- Test -->
